### ISSUE TITLE
Layer-4 virtual service should not refer to any HTTP policyset

### ISSUE THREAD

**Issue by MikeVL** [avinetworks/devops#290]
```
Error from certificate management service: STDOUT - "
Running version 0.9.7 
dry_run is: False 
disable_check is: False 
directory_url is https://acme-v02.api.letsencrypt.org/directory Contact set to: ['mailto:*****'] 
Parsing account key... Parsing CSR... Found domains: *****
Getting directory... Directory found!
Registering account... Already registered! 
Updated contact details: mailto:*****
Creating new order... Order created! 
Verifying *****... 
Found VS virtualservice-2ff1e71f-31ea-4036-8621-0aa6920e462e with fqdn *****
Created httpPolicy with uuid httppolicyset-9799003c-db58-4358-a6a1-c1c6eb270f81 
Adding port 80 to VS 
Cleaning up... 
Removed httpPolicySet from VS virtualservice-2ff1e71f-31ea-4036-8621-0aa6920e462e Deleted httpPolicySet ". 

STDERR - "
/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings 
warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings 
warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings warnings.warn(( Traceback (most recent call last): 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 576, in <module> cert = certificate_request(csr, common_name, kwargs) 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 547, in certificate_request signed_crt = get_crt(user, password, tenant, api_version, csr_temp_file.name, 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 402, in get_crt _do_request_avi("virtualservice/{}".format(vs_uuid), "PATCH", patch_data) 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 156, in _do_request_avi err = error_msg + " url - {}. Method - {}. Response status - {}. Response - {}".format(url, method, rsp.status_code, rsp.json()) 
File "/opt/avi/python/lib/avi/sdk/avi_api.py", line 122, in json raise APIError('HTTP Error: %d Error Msg %s' % ( avi.sdk.avi_api.APIError: ('HTTP Error: 400 Error Msg {"error": "Layer-4 virtual service should not refer to any HTTP policyset"}', <Response [400]>) Error in sys.excepthook: Traceback (most recent call last): 
File "/usr/local/lib/python3.8/dist-packages/avi_traceback/avi_exception_hook.py", line 51, in avi_excepthook os.makedirs(output_dir) 
File "/usr/lib/python3.8/os.py", line 223, in makedirs mkdir(name, mode) OSError: [Errno 30] Read-only file system: '/var/lib/avi/python_crash' Original exception was: Traceback (most recent call last): File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 576, in <module> cert = certificate_request(csr, common_name, kwargs) 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 547, in certificate_request signed_crt = get_crt(user, password, tenant, api_version, csr_temp_file.name, 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 402, in get_crt _do_request_avi("virtualservice/{}".format(vs_uuid), "PATCH", patch_data) 
File "/run/shm/cs/certificatemanagementprofile-daa621d8-50f0-4193-b468-f1b1b08321a8", line 156, in _do_request_avi err = error_msg + " url - {}. Method - {}. Response status - {}. Response - {}".format(url, method, rsp.status_code, rsp.json()) File "/opt/avi/python/lib/avi/sdk/avi_api.py", line 122, in json raise APIError('HTTP Error: %d Error Msg %s' % ( avi.sdk.avi_api.APIError: ('HTTP Error: 400 Error Msg {"error": "Layer-4 virtual service should not refer to any HTTP policyset"}', <Response [400]>) "..
```

**Comment by patschi** [comment]
Expected. The script can only work with L7 virtual services.
